replicaCount: 1

#namespace: "default"

image:
  #registry: local
  #repository: image-registry.openshift-image-registry.svc:5000/oaicicd-tmp/gnbsim
  repository: gnbsim
  version: latest
  pullPolicy: Never

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: "oai-gnbsim-sa"

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

securityContext:
  privileged: true

service:
  type: ClusterIP
  http1Port: 80

start:
  gnbsim: true

multus:
  ngapIPadd: "192.168.74.198"
  ngapNetmask: "24"
  ngapGateway: "192.168.74.1"
  gtpIPadd: "192.168.75.198"
  gtpNetmask: "24"
  gtpGateway: "192.168.75.1"

config:
  mcc: "208"
  mnc: "95"
  gnbid: "1"
  tac: "0x00a000"
  sst: "130"
  sd: "000082"
  pagingdrx: "v32"
  ranuengapid: "0"
  imeisv: "35609204079514"
  msin: "0000000031"
  routingindicator: "1234"
  protectionscheme: "null"
  key: "0C0A34601D4F07677303652C0462535B"
  opc: "63bfa50ee6523365ff14c1f45f88737d"
  dnn: "oai-ipv4"
  url: "http://192.168.76.205:8000"
  nrcellid: "1"
  use_fqdn: "yes"
  amf_fqdn: "oai-amf-svc"
  ngappeeraddr: "oai-amf-svc"
  gtpulocaladdr: "status.podIP"
  gtpuifname: "eth0"
persistence:
  enabled: false

resources: 
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

nodeName:
